### ISSUE TITLE
False N + 1 warnings on Rails 4.2

### ISSUE THREAD

**Issue by ivanoblomov** [flyerhzm/bullet#203]
For a Claim that has one Carrier, which in turn has many Users, we get the following warning:

    N+1 Query detected
      Carrier => [:users]
      Add to your finder: :include => [:users]

For this line of code:

    claim.company.users.sort_by { |u| u.name }

Note that the Claim is loaded by a standard CRUD ClaimsController#edit action. Only one Claim is read from the database; no looping across multiple records occur.

This may be related to https://github.com/flyerhzm/bullet/issues/201.

**Comment by dankohn** [comment]
(I work with @ivanoblomov.) Please note that the identical controller code doesn't trigger the N+1 warning with Rails 4.1.9, so this issue is potentially related to Adequate Record.

**Comment by ivanoblomov** [comment]
Here's another data point: whitelisting to-one associations that trigger the warning has no effect.

**Comment by kreintjes** [comment]
I can confirm these issues. In my controller I perform the following code: `@organisation = Organisation.find(params[:organisation_id])`. Then in my views, I render two (collection) selects using the following code:

```
f.collection_select :client_id, @organisation.clients, :id, :name
f.select :project_id, @organisation.projects.map { |p| [p.name, p.id, { data: { client_id: p.client_id } } ]}
```

This results in two bullet warnings:
```
N+1 Query detected
  Organisation => [:clients]
  Add to your finder: :include => [:clients]

N+1 Query detected
  Organisation => [:projects]
  Add to your finder: :include => [:projects]
```

I have various similar problems as well. Although, some seem to be related to CanCanCan, because when I change my ability file to only include `can :manage, :all`, they are gone. However, when I downgrade to Rails 4.1.9, all issues are gone as well.

**Comment by flyerhzm** [comment]
@ivanoblomov @dankohn @kreintjes I have fixed it in master branch, please try and let me know if it works

**Comment by kreintjes** [comment]
@flyerhzm It does not seem to work. I get the same (false) results as before.

**Comment by flyerhzm** [comment]
@kreintjes I have added a test for such case, and it's padded in both rails 4.19 and 4.2.0

https://github.com/flyerhzm/bullet/blob/master/spec/integration/active_record4/association_spec.rb#L518

could you try to reproduce the issue in tests?

**Comment by kreintjes** [comment]
@flyerhzm I believe I have identified the difference.

In my data model I have an Organisation model which has many Users (through the OrganisationUser model). When I use `Organisation.first.users.inspect` (in a view) I get no Bullet warning (as expected). However, when I perform `Organisation.find(1).users.inspect`, I do get a (false) bullet warning:

```
N+1 Query detected
  Organisation => [:users]
  Add to your finder: :includes => [:users]
```

**Comment by flyerhzm** [comment]
@kreintjes sorry I didn't reproduce your issue, is it possible you can add a test or a demo project to reproduce your issue?

**Comment by kreintjes** [comment]
@flyerhzm The problem seems to be more complicated then I thought at first. It appears the the CanCanCan authorization gem is also somehow involved. I am not sure if the problem is in Bullet or CanCanCan (or Rails 4.2), but as far a I can tell there are no actual N+1 queries (although my code may not be great performance wise). Also, when running my application in Rails 4.1.9 Bullet does not raise these N+1 query warnings. The problem is a bit difficult to explain, but I will try.

Suppose you have an application with three models: `Organisation`, `User` and `Project`. An organisation has many Users and Projects (and an user/project belongs to an organisation). In my ability file I have defined one ability as follows: `can :manage, User, organisation: { users: { id: user.id } }`. This makes sure Users can only manage other users belonging to the same organisation.

Now the problem is as follows. If we have a call like `@organisation.projects` (where @organisation is retrieved using `Organisation.find(1)`) or `Organisation.find(1).projects`, then Bullet does not complain about an N+1 query (as expected). However, if before that we do authorization call on an model involving an authorization, then Bullet does complain about an N+1 query (both on the authorization call, as well as on any other calls on an organisation). For example, if we have `authorize!(:read, User.first)` or `can?(:read, User.first)` in the controller or view, then we get an N+1 warning about this call, but also about subsequent calls on the Organisation the user belongs to (thus calls like `@organisation.projects` or `Organisation.find(1).projects`). Strangely enough however, we do not get a warning about a call like `Organisation.first.projects`, even though `@organisation`, `Organisation.find(1)` and `Organisation.first` are all the same organisation.

To illustrate the problem, I have created a demo app here: https://github.com/kreintjes/bullet-demo. It contains the discussed Organisation, User and Project model, as well as the ability file. In the Test controller and corresponding index view, I perform some code to illustrate the problems. Also see the comments in these files. To run the app simple run bundle followed by rake db:setup. When going to the root url of the problem, you directly see the bullet warnings I am referring to.

I also created a rails-4-1 branch, which uses Rails 4.1.9, in which the N+1 warnings are not present.

I hope I'm explaining the issue clearly. If not, please let me know. Please also let me know if I am doing something wrong or the problem lays within the CanCanCan gem.

**Comment by atipugin** [comment]
I'm experiencing same issue, any progress on this?

**Comment by flyerhzm** [comment]
@kreintjes thanks for building a demo, really helpful for me. I have fixed in bullet 4.14.4.

@ivanoblomov @atipugin please let me know if it also works for you.

**Comment by kreintjes** [comment]
@flyerhzm You're welcome!

It works like a charm now. Thank you very much for fixing it!

**Comment by JohnColvin** [comment]
We are still seeing this issue on rails 4.2 and bullet 4.14.4. We're also using cancancan. Here are the models involved and their relevant relationships:
```ruby
class User < ActiveRecord::Base
  belongs_to :account
end

class Account < ActiveRecord::Base
  has_many :users
  has_one :subscription
end

class Subscription < ActiveRecord::Base
  belongs_to :account
end
```

In the ability file, when accessing `user.account.subscription`, we see this bullet warning:
```
N+1 Query detected
  Account => [:subscription]
  Add to your finder: :includes => [:subscription]
```

Thanks for your help!

**Comment by kreintjes** [comment]
@flyerhzm I can confirm @JohnColvin 's issue. I am also still seeing this problem in a few cases. Many cases are fixed with Bullet 4.14.4, but unfortunately not in all cases. I am not exactly sure what the difference is between the cases that do work and those that do not.

**Comment by zerocool4u2** [comment]
Hi, some info that might help.
In my case i have a polymorphic association called avatar with an image, 

     class User < ActiveRecord::Base
          has_one :avatar, as: :resource, dependent: :destroy
          accepts_nested_attributes_for :avatar

          has_many :artists, dependent: :destroy
     end
     class Artist < ActiveRecord::Base
          has_one :avatar, as: :resource, dependent: :destroy
          accepts_nested_attributes_for :avatar
          belongs_to :user, counter_cache: true
     end

     class Avatar < ActiveRecord::Base
          belongs_to :resource, polymorphic: true
          #paperclip
          has_attached_file :image, styles: { xs: "100x100#", s: "200x200#", m: "400x400#", l: "600x600#", xl: "800x800#" },
          url: "/assets/images/avatars/:id/:style/:id.:extension",
          path: ":rails_root/public/assets/images/avatars/:id/:style/:id.:extension"
     end

the n+1 query is trigger when i load all the artists from an user, because in each one is loading also his corresponding avatar, so i guest is kinda acting like a n+1 query because of the multiple consecutive calls

     N+1 Query detected
          Artist => [:avatar]
          Add to your finder: :includes => [:avatar]
     N+1 Query method call stack

i don't know how are the queries been detected, but maybe do a comparative between 

     Artist.reflect_on_all_associations(:has_one).map(&:name).include?(:avatar)

and trigger the n+1 if false, I’m guessing that you already have the class and association names, regards!
