### ISSUE TITLE
false positive on `create`

### ISSUE THREAD

**Issue by mockdeep** [flyerhzm/bullet#204]
I'm getting false positives when I try to create a record and reference associated records before create:

campaign.rb:

```ruby
class Campaign < ActiveRecord::Base
  belongs_to :user

  scope :draft, -> { where(draft: true) }

  validates :user, presence: true
end
```

```ruby
user.campaigns.draft.first_or_create
```

```
N+1 Query detected
  Campaign => [:user]
  Add to your finder: :include => [:user]
N+1 Query method call stack
  .../app/controllers/routing_wizard_controller.rb:69:in `locate_campaign'
```

**Comment by leonelgalan** [comment]
:+1: Me too! Thanks for posting it, this is very well explained.

**Comment by flyerhzm** [comment]
@mockdeep @leonelgalan are you working with rails 4.2, I just fixed an issue in master branch, could you try it and let me know if it also fixed yours?

**Comment by mockdeep** [comment]
@flyerhzm Just tried it on the latest master and still seeing the same issue. I'm on Rails 4.1.

**Comment by ivanoblomov** [comment]
We're seeing this too on 4.1.8 and are whitelisting it for now...

        Bullet.add_whitelist type: :n_plus_one_query,
                             class_name: class_name,
                             association: association

The error only cropped up in the last week. Not sure what the deltas were.

**Comment by flyerhzm** [comment]
@mockdeep I failed to reproduce your issue, could you try to add a test to help me figure it out?

**Comment by leonelgalan** [comment]
Hi @flyerhzm, I just tried master with my setup (4.2) and still failing. I'll try to create minimal app that reproduces the error or a test if that's simpler. I might have some time later today to do that.

**Comment by leonelgalan** [comment]
I'm unable to create a N+1 Query detection on my sample app:


```ruby
    author = Author.create(name: 'Leonel')
    author.posts.create(title: 'Hello World!')
    author.posts.create(title: 'Hello World 2!')

    author = Author.create(name: 'Rob')
    author.posts.create(title: 'Hello World!')
    author.posts.create(title: 'Hello World 2!')

    Author.all.map { |a| [a.name, a.posts.inspect] } 
```

My `environments/test.rb` has this at the end:

```ruby
  config.after_initialize do
    Bullet.enable = true
    Bullet.bullet_logger = true
    Bullet.raise = true
  end
```

I was expecting an exception to be raised. I was trying to force an exception, before I attempted to model exactly the issue described here.

**Comment by mockdeep** [comment]
Okay, I think I have it nailed down. I tossed in the scope above thinking that might be related, but we also have a default scope in our class. When I remove that I don't get the message anymore:

```ruby
class Campaign < ActiveRecord::Base
  belongs_to :user

  scope :draft, -> { where(draft: true) }

  default_scope { where(deleted_at: nil) }

  validates :user, presence: true
end
```

**Comment by mockdeep** [comment]
Hmm, I'm trying to reproduce it in the specs and not having much luck. There's another interaction that appears to be related. I'll have to gut our app and see if I can nail down the exact situation. It seems to be related to the default scope with the presence validation, but there's also an STI relation being instantiated at the same time...

**Comment by mockdeep** [comment]
Okay, after much ado, I have a repro. [Here is a basic app](https://github.com/mockdeep/bullet_repro) that demonstrates what I'm seeing. It looks like some combination of the validations, scope, and instantiating the new relation cause the issue. You just need to do a `rake db:setup` and boot up the server and you should see `Bullet::Notification::UnoptimizedQueryError in HomeController#index`.

**Comment by flyerhzm** [comment]
@mockdeep Thanks for creating an app to reproduce the issue, it's really helpful for me to find out the issue, I have fixed it in bullet 4.14.3, please let me know if it solves your problem.

**Comment by mockdeep** [comment]
@flyerhzm Yep that did the trick. Thanks for such a quick turnaround!
